Repository ZupIT/horusec, pull requests merged in 2020-11, with the labels that each got.

#112 Feature/auth grpc
  deployments/docker-compose.dev.yaml
  deployments/docker-compose.test.yaml
  deployments/docker-compose.yaml
  development-kit/pkg/enums/errors/auth.go
  development-kit/pkg/services/grpc/auth/auth.pb.go
  development-kit/pkg/services/grpc/auth/auth.proto
  development-kit/pkg/services/grpc/auth/mock.go
  development-kit/pkg/services/middlewares/horusec_authz.go
  development-kit/pkg/services/middlewares/horusec_authz_test.go
  e2e/deployments/docker-compose.yaml
  e2e/server/http_test.go
  e2e/server/requests.go
  go.mod
  go.sum
  horusec-account/README.md
  horusec-account/cmd/app/main.go
  horusec-account/config/grpc/grpc.go
  horusec-account/internal/router/route_test.go
  horusec-account/internal/router/router.go
  horusec-analytic/README.md
  horusec-analytic/cmd/app/main.go
  horusec-analytic/config/grpc/grpc.go
  horusec-analytic/internal/router/route_test.go
  horusec-analytic/internal/router/router.go
  horusec-api/README.md
  horusec-api/cmd/app/main.go
  horusec-api/config/grpc/grpc.go
  horusec-api/internal/router/route_test.go
  horusec-api/internal/router/router.go
  horusec-auth/README.md
  horusec-auth/cmd/app/main.go
  horusec-auth/config/admin/admin.go
  horusec-auth/config/grpc/grpc.go
  horusec-auth/internal/controller/auth/auth.go
  horusec-auth/internal/controller/auth/auth_mock.go
  horusec-auth/internal/controller/auth/auth_test.go
  horusec-auth/internal/handler/auth/auth.go
  horusec-auth/internal/handler/auth/auth_test.go
  horusec-auth/internal/router/router.go
Labels: enhancement

#102 Feature/improving test
  .github/workflows/e2e.yml
  Makefile
  development-kit/pkg/entities/account/invite_user.go
  development-kit/pkg/entities/account/invite_user_test.go
  development-kit/pkg/entities/account/roles/account_company.go
  development-kit/pkg/entities/account/roles/account_company_test.go
  development-kit/pkg/entities/api/dto/update_vuln_type.go
  development-kit/pkg/entities/api/dto/update_vuln_type_test.go
  development-kit/pkg/services/keycloak/keycloak.go
  e2e/TESTBOOK.md
  e2e/application_admin/horusec/http_test.go
  e2e/application_admin/horusec/requests.go
  e2e/application_admin/keycloak/http_test.go
  e2e/application_admin/ldap/http_test.go
  e2e/cli/scan_languages/scan_languages_test.go
  e2e/deployments/docker-compose.application-admin.horusec.yaml
  e2e/deployments/docker-compose.server.horusec.yaml
  e2e/deployments/docker-compose.server.keycloak.yaml
  e2e/deployments/docker-compose.server.messages.yaml
  e2e/server/horusec/http_test.go
  e2e/server/horusec/requests.go
  e2e/server/http_test.go
  e2e/server/keycloak/entities/user_representation.go
  e2e/server/keycloak/http_test.go
  e2e/server/keycloak/requests.go
  e2e/server/ldap/http_test.go
  e2e/server/messages/messages_test.go
  e2e/server/messages/requests.go
  e2e/server/requests.go
  e2e/server/shared_requests.go
  go.mod
  go.sum
  horusec-account/internal/controller/companies/companies.go
  horusec-config.json
Labels: enhancement

#115 [WIP] Fixing e2e
  .github/workflows/e2e.yml
  deployments/docker-compose.dev.yaml
  development-kit/pkg/entities/auth/credentials.go
  development-kit/pkg/entities/auth/credentials_test.go
  e2e/application_admin/horusec/http_test.go
  e2e/application_admin/horusec/requests.go
  e2e/deployments/docker-compose.application-admin.horusec.yaml
  e2e/server/horusec/http_test.go
  e2e/server/horusec/requests.go
  e2e/server/keycloak/http_test.go
  e2e/server/keycloak/requests.go
  e2e/server/messages/messages_test.go
  e2e/server/messages/requests.go
Labels: bug

#116 Fixing repository authz groups
  e2e/server/horusec/http_test.go
  e2e/server/keycloak/http_test.go
  e2e/server/keycloak/requests.go
  horusec-account/internal/controller/repositories/repositories.go
  horusec-account/internal/controller/repositories/repositories_test.go
  horusec-auth/internal/controller/auth/auth_test.go
  horusec-auth/internal/services/ldap/ldap_test.go
Labels: bug

#125 Hidden application admin email when option is disabled.
  horusec-manager/src/pages/Internal/Company/Add/index.tsx
Labels: bug

#140 Feature/update docs
  .github/workflows/deploy-service.yml
  deployments/docker-compose.dev.yaml
  deployments/docker-compose.test.yaml
  deployments/docker-compose.yaml
  deployments/scripts/update-image-service.sh
  e2e/deployments/docker-compose.application-admin.horusec.yaml
  e2e/deployments/docker-compose.server.horusec.yaml
  e2e/deployments/docker-compose.server.keycloak.yaml
  e2e/deployments/docker-compose.server.messages.yaml
  horusec-account/README.md
  horusec-account/deployments/docker-compose.yaml
  horusec-analytic/deployments/docker-compose.yaml
  horusec-api/README.md
  horusec-api/deployments/docker-compose.yaml
  horusec-auth/README.md
  horusec-auth/config/app/app.go
  horusec-auth/deployments/docker-compose.yaml
  horusec-auth/internal/controller/account/account_test.go
  horusec-cli/README.md
  horusec-webhook/.semver.yaml
Labels: documentation

#146 Javascritpt eslint security
  .github/workflows/deploy-cli-tools.yml
  README.md
  deployments/dockerfiles/eslint/.semver.yaml
  deployments/dockerfiles/eslint/Dockerfile
  deployments/scripts/update-image-tool.sh
  development-kit/pkg/entities/analyser/eslint/output.go
  development-kit/pkg/enums/tools/tools.go
  development-kit/pkg/usecases/analysis/analysis.go
  horusec-cli/cmd/horusec/start/start.go
  horusec-cli/internal/controllers/analyser/analyser.go
  horusec-cli/internal/services/formatters/javascript/eslint/config.go
  horusec-cli/internal/services/formatters/javascript/eslint/formatter.go
  horusec-cli/internal/services/formatters/javascript/eslint/formatter_test.go
Labels: enhancement

#156 Bugfix/link vulnerablity code
  horusec-cli/internal/controllers/printresults/print_results.go
Labels: enhancement

#136 [Frontend] Webhook improvements
  horusec-manager/src/config/i18n/enUS.json
  horusec-manager/src/config/i18n/ptBR.json
  horusec-manager/src/pages/Internal/Home/Webhooks/Add/index.tsx
  horusec-manager/src/pages/Internal/Home/Webhooks/Add/styled.ts
  horusec-manager/src/pages/Internal/Home/Webhooks/Edit/index.tsx
  horusec-manager/src/pages/Internal/Home/Webhooks/Edit/styled.ts
  horusec-manager/src/pages/Internal/Home/Webhooks/index.tsx
  horusec-manager/src/pages/Internal/Home/Webhooks/styled.ts
Labels: enhancement
