Repository ZupIT/horusec, pull requests merged in 2020-12, with the labels that each got.

#161 Adding support for root path horusec-config file
  horusec-cli/cmd/horusec/main.go
Labels: bug

#137 Settings screen
  Makefile
  development-kit/pkg/databases/relational/repository/account/account.go
  development-kit/pkg/entities/auth/account.go
  development-kit/pkg/entities/auth/account_test.go
  development-kit/pkg/entities/auth/config_auth.go
  development-kit/pkg/services/grpc/auth/auth.pb.go
  horusec-auth/config/admin/admin_test.go
  horusec-auth/config/app/app.go
  horusec-auth/config/cors/cors.go
  horusec-auth/internal/controller/account/account.go
  horusec-auth/internal/controller/account/account_test.go
  horusec-auth/internal/controller/auth/auth.go
  horusec-auth/internal/handler/account/account_test.go
  horusec-auth/internal/handler/auth/auth.go
  horusec-manager/src/assets/svg/config.svg
  horusec-manager/src/components/SideMenu/index.tsx
  horusec-manager/src/components/SideMenu/styled.ts
  horusec-manager/src/config/i18n/enUS.json
  horusec-manager/src/config/i18n/ptBR.json
  horusec-manager/src/helpers/hooks/useResponseMessage.ts
  horusec-manager/src/pages/Internal/Home/Settings/ChangePassword/index.tsx
  horusec-manager/src/pages/Internal/Home/Settings/ChangePassword/styled.ts
  horusec-manager/src/pages/Internal/Home/Settings/Edit/index.tsx
  horusec-manager/src/pages/Internal/Home/Settings/Edit/styled.ts
  horusec-manager/src/pages/Internal/Home/Settings/index.tsx
  horusec-manager/src/pages/Internal/Home/Settings/styled.ts
  horusec-manager/src/routes/home.routes.tsx
  horusec-manager/src/services/account.ts
Labels: enhancement

#173 [Hotfix] - Horusec Logo in template emails.
  horusec-messages/internal/controllers/email/templates/email_confirmation.go
  horusec-messages/internal/controllers/email/templates/organization_invite.go
  horusec-messages/internal/controllers/email/templates/reset_password.go
Labels: bug

#175 Front-end - Disabled broker rules
  horusec-manager/src/components/SideMenu/index.tsx
  horusec-manager/src/config/i18n/enUS.json
  horusec-manager/src/config/i18n/ptBR.json
  horusec-manager/src/helpers/interfaces/HorusecConfig.ts
  horusec-manager/src/helpers/interfaces/InternalRoute.ts
  horusec-manager/src/helpers/localStorage/horusecConfig.ts
  horusec-manager/src/pages/External/Auth/Horusec/CreateAccount/Password/index.tsx
  horusec-manager/src/pages/External/Auth/Horusec/Login/index.tsx
  horusec-manager/src/pages/Internal/Home/Settings/Edit/index.tsx
Labels: enhancement

#179 Frontend - Donut charts error
  horusec-manager/src/pages/Internal/Home/Dashboard/AllVulnerabilities/index.tsx
  horusec-manager/src/pages/Internal/Home/Dashboard/AllVulnerabilities/styled.ts
  horusec-manager/src/pages/Internal/Home/Dashboard/VulnerabilitiesByLanguage/index.tsx
  horusec-manager/src/pages/Internal/Home/Dashboard/VulnerabilitiesByLanguage/styled.ts
Labels: bug

#184 [Frontend] - Adjusting SVG icons
  horusec-manager/src/assets/svg/delete.svg
  horusec-manager/src/assets/svg/edit.svg
  horusec-manager/src/assets/svg/list.svg
  horusec-manager/src/assets/svg/no-view.svg
  horusec-manager/src/assets/svg/plus.svg
  horusec-manager/src/assets/svg/view.svg
  horusec-manager/src/assets/svg/webhook.svg
  horusec-manager/src/components/SideMenu/index.tsx
Labels: enhancement

#185 [Frontend] Clear inputs when create webhook
  horusec-manager/src/pages/Internal/Home/Webhooks/Add/index.tsx
  horusec-manager/src/pages/Internal/Home/Webhooks/index.tsx
Labels: bug

#211 Frontend - MomentJS replacement with date-fns
  horusec-manager/package-lock.json
  horusec-manager/package.json
  horusec-manager/src/config/axios/default.ts
  horusec-manager/src/helpers/formatters/chartData.ts
  horusec-manager/src/helpers/formatters/date.ts
  horusec-manager/src/helpers/localStorage/tokens.ts
  horusec-manager/src/pages/Internal/Company/List/Tokens/index.tsx
  horusec-manager/src/pages/Internal/Home/Repositories/Tokens/index.tsx
Labels: dependencies

#219 Get viper file config path and setup on command start initialize
  horusec-cli/cmd/horusec/main.go
  horusec-cli/cmd/horusec/start/start.go
  horusec-cli/cmd/horusec/start/start_test.go
  horusec-cli/config/config.go
  horusec-cli/config/config_mock.go
  horusec-cli/config/config_test.go
  horusec-cli/config/entity.go
  horusec-cli/config/interface.go
  horusec-cli/internal/helpers/messages/debug.go
  horusec-cli/internal/helpers/messages/error.go
  horusec-cli/internal/helpers/messages/panic.go
  horusec-cli/internal/usecases/cli/cli_test.go
  horusec-config.json
Labels: enhancement

#229 Improvements in workspace
  horusec-manager/.env.example
  horusec-manager/src/assets/svg/warning.svg
  horusec-manager/src/components/Counter/index.tsx
  horusec-manager/src/components/Counter/styled.ts
  horusec-manager/src/components/Flash/index.tsx
  horusec-manager/src/components/Flash/styled.ts
  horusec-manager/src/config/i18n/enUS.json
  horusec-manager/src/config/i18n/ptBR.json
  horusec-manager/src/config/themes/dark.ts
  horusec-manager/src/contexts/FlashMessage.tsx
  horusec-manager/src/contexts/Workspace.tsx
  horusec-manager/src/helpers/enums/flashMessageType.ts
  horusec-manager/src/helpers/interfaces/FilterValues.ts
  horusec-manager/src/pages/Internal/Dashboard/Filters/index.tsx
  horusec-manager/src/pages/Internal/Dashboard/TotalDevelopers/index.tsx
  horusec-manager/src/pages/Internal/Dashboard/index.tsx
  horusec-manager/src/pages/Internal/index.tsx
  horusec-manager/src/services/analytic.ts
Labels: enhancement

#231 Frontend - Linkify vulnerabilities details
  horusec-manager/package-lock.json
  horusec-manager/package.json
  horusec-manager/src/config/endpoints.ts
  horusec-manager/src/pages/Internal/Vulnerabilities/Details/index.tsx
  horusec-manager/src/pages/Internal/Vulnerabilities/Details/styled.ts
Labels: enhancement

#245 Update deploy-service.yml
  .github/workflows/deploy-service.yml
Labels: bug
