Repository ZupIT/horusec, pull requests merged in 2021-01, with the labels that each got.

#255 Frontend - Fixed ranges options when select dates of dashboard
  horusec-manager/src/components/Calendar/index.tsx
  horusec-manager/src/components/Calendar/styled.ts
  horusec-manager/src/config/i18n/enUS.json
  horusec-manager/src/config/i18n/ptBR.json
  horusec-manager/src/pages/Internal/Dashboard/Filters/index.tsx
  horusec-manager/src/pages/Internal/Dashboard/Filters/styled.ts
Labels: enhancement

#273 [Frontend] Fixing bugs found in production
  horusec-manager/src/components/Logout/index.tsx
  horusec-manager/src/components/Pagination/index.tsx
  horusec-manager/src/components/Splash/styled.ts
  horusec-manager/src/contexts/Auth/index.tsx
  horusec-manager/src/contexts/Auth/keycloak.ts
  horusec-manager/src/helpers/localStorage/tokens.ts
  horusec-manager/src/layouts/External/styled.ts
  horusec-manager/src/pages/Internal/Dashboard/VulnerabilitiesDetails/index.tsx
  horusec-manager/src/pages/Internal/Vulnerabilities/index.tsx
Labels: bug

#274 [Frontend] Hidden invite user - Ldap
  horusec-manager/src/pages/Internal/Repositories/index.tsx
  horusec-manager/src/pages/Internal/Workspaces/index.tsx
Labels: improvement

#266 Dart
  .github/workflows/dart-pipeline.yml
  Makefile
  development-kit/pkg/engines/csharp/regular/regular.go
  development-kit/pkg/engines/csharp/rules.go
  development-kit/pkg/engines/dart/and/and.go
  development-kit/pkg/engines/dart/or/or.go
  development-kit/pkg/engines/dart/regular/regular.go
  development-kit/pkg/engines/dart/rules.go
  development-kit/pkg/engines/dart/rules_test.go
  development-kit/pkg/engines/java/rules.go
  development-kit/pkg/engines/jvm/or/or.go
  development-kit/pkg/engines/kotlin/rules.go
  development-kit/pkg/engines/kubernetes/rules.go
  development-kit/pkg/enums/languages/languages.go
  development-kit/pkg/enums/languages/languages_test.go
  development-kit/pkg/enums/tools/tools.go
  development-kit/pkg/services/ldap/ldap.go
  development-kit/pkg/usecases/analysis/analysis.go
  e2e/cli/scan_languages/scan_languages_test.go
  examples/dart/example1/lib/data/database_helper.dart
  examples/dart/example1/lib/data/query/user_ctr.dart
  examples/dart/example1/lib/main.dart
  examples/dart/example1/lib/models/user.dart
  examples/dart/example1/lib/screens/home_pages.dart
  examples/dart/example1/lib/services/request/user_request.dart
  examples/dart/example1/lib/services/response/user_response.dart
  examples/dart/example1/lib/utils/cripto_util.dart
  examples/dart/example1/lib/utils/network_util.dart
  horusec-cli/internal/controllers/analyser/analyser.go
  horusec-cli/internal/controllers/language_detect/language_detect.go
  horusec-cli/internal/services/formatters/dart/horusecdart/formatter.go
  horusec-cli/internal/services/formatters/dart/horusecdart/formatter_test.go
  horusec-config.json
  horusec-csharp/README.md
  horusec-dart/.semver.yaml
  horusec-dart/README.md
  horusec-dart/cmd/app/main.go
  horusec-dart/deployments/Dockerfile
  horusec-dart/internal/controllers/analysis.go
  horusec-dart/internal/controllers/analysis_test.go
  horusec-java/README.md
  horusec-kotlin/README.md
  horusec-kubernetes/README.md
  horusec-leaks/README.md
  horusec-manager/src/config/themes/dark.ts
  horusec-nodejs/README.md
Labels: enhancement

#285 Dashboard load data from the beginning
  development-kit/pkg/databases/relational/repository/analysis/analysis.go
  horusec-analytic/internal/handlers/dashboard/dashboard.go
  horusec-analytic/internal/handlers/dashboard/dashboard_test.go
  horusec-manager/src/components/Pagination/index.tsx
  horusec-manager/src/helpers/formatters/date.ts
  horusec-manager/src/pages/Internal/Dashboard/Filters/index.tsx
  horusec-manager/src/services/analytic.ts
Labels: enhancement

#294 Added elixir and shell colors in languages of dashboard
  horusec-manager/src/config/themes/dark.ts
Labels: enhancement
