Repository ZupIT/horusec, pull requests merged in 2021-03, with the labels that each got.

#374 change defaulthttp to http, add type error in catch
  horusec-manager/src/pages/Internal/Vulnerabilities/index.tsx
  horusec-manager/src/services/repository.ts
Labels: bug

#376 Keycloack auth flow
  deployments/docker-compose-network-host.yaml
  deployments/docker-compose.dev.yaml
  deployments/docker-compose.test.yaml
  deployments/docker-compose.yaml
  horusec-manager/src/config/axios.ts
  horusec-manager/src/config/i18n/enUS.json
  horusec-manager/src/config/i18n/ptBR.json
  horusec-manager/src/helpers/localStorage/tokens.ts
  horusec-manager/src/pages/External/Auth/Keycloak/index.tsx
Labels: bug

#375 Change type actions property
  horusec-manager/src/pages/Internal/Workspaces/Users/index.tsx
Labels: bug

#380 fix broken actions on datatable
  horusec-manager/src/components/Datatable/index.tsx
  horusec-manager/src/components/Datatable/styled.tsx
  horusec-manager/src/components/Pagination/styled.ts
  horusec-manager/src/pages/Internal/Workspaces/index.tsx
Labels: bug

#382 Feature/cleanup async request in useffect
  horusec-manager/src/components/SideMenu/index.tsx
  horusec-manager/src/helpers/hooks/useResponseMessage.ts
  horusec-manager/src/pages/Internal/Dashboard/AllVulnerabilities/index.tsx
  horusec-manager/src/pages/Internal/Dashboard/Filters/index.tsx
  horusec-manager/src/pages/Internal/Dashboard/TotalDevelopers/index.tsx
  horusec-manager/src/pages/Internal/Dashboard/TotalRepositories/index.tsx
  horusec-manager/src/pages/Internal/Dashboard/VulnerabilitiesByDeveloper/index.tsx
  horusec-manager/src/pages/Internal/Dashboard/VulnerabilitiesByLanguage/index.tsx
  horusec-manager/src/pages/Internal/Dashboard/VulnerabilitiesByRepository/index.tsx
  horusec-manager/src/pages/Internal/Dashboard/VulnerabilitiesDetails/index.tsx
  horusec-manager/src/pages/Internal/Dashboard/VulnerabilitiesTimeLine/index.tsx
  horusec-manager/src/pages/Internal/Repositories/index.tsx
  horusec-manager/src/pages/Internal/Vulnerabilities/index.tsx
Labels: improvement

#390 Update rule of alert, confirm and prompt methods to get correctly pos…
  development-kit/pkg/engines/nodejs/regular/regular.go
  development-kit/pkg/engines/nodejs/regular/regular_test.go
  development-kit/pkg/enums/tools/tools_test.go
  examples/javascript/example4/test.js
  go.sum
  horusec-config.json
Labels: bug

#397 Severity levels presentation in manager
  horusec-manager/src/config/themes/dark.ts
  horusec-manager/src/helpers/formatters/chartData.ts
  horusec-manager/src/pages/Internal/Vulnerabilities/index.tsx
Labels: enhancement

#400 [Manager] remove logic that causes multiple requests
  horusec-manager/src/components/Select/index.tsx
  horusec-manager/src/pages/Internal/Vulnerabilities/index.tsx
Labels: bug

#408 [BUGFIX] [MANAGER] - fix requests repositories and workspaces
  horusec-manager/src/config/i18n/enUS.json
  horusec-manager/src/config/i18n/ptBR.json
  horusec-manager/src/pages/Internal/Dashboard/Filters/index.tsx
  horusec-manager/src/pages/Internal/Repositories/index.tsx
  horusec-manager/src/pages/Internal/Settings/ChangePassword/index.tsx
  horusec-manager/src/pages/Internal/Settings/index.tsx
  horusec-manager/src/pages/Internal/Workspaces/index.tsx
Labels: bug

#411 [HOTFIX] Set default variable isloading to false
  horusec-manager/src/pages/Internal/Dashboard/AllVulnerabilities/index.tsx
  horusec-manager/src/pages/Internal/Dashboard/TotalDevelopers/index.tsx
  horusec-manager/src/pages/Internal/Dashboard/VulnerabilitiesByDeveloper/index.tsx
  horusec-manager/src/pages/Internal/Dashboard/VulnerabilitiesByLanguage/index.tsx
  horusec-manager/src/pages/Internal/Dashboard/VulnerabilitiesByRepository/index.tsx
  horusec-manager/src/pages/Internal/Dashboard/VulnerabilitiesDetails/index.tsx
  horusec-manager/src/pages/Internal/Dashboard/VulnerabilitiesTimeLine/index.tsx
  horusec-manager/src/pages/Internal/Repositories/Invite/index.tsx
  horusec-manager/src/pages/Internal/Repositories/Tokens/index.tsx
  horusec-manager/src/pages/Internal/Vulnerabilities/index.tsx
  horusec-manager/src/pages/Internal/Workspaces/Tokens/index.tsx
Labels: enhancement

#359 Updating docs
  README.md
  assets/horusec-account.jpg
  assets/horusec-analysis-cli.jpg
  assets/horusec-analytic.jpg
  assets/horusec-api.jpg
  assets/horusec-auth.jpg
  assets/horusec-cli.jpg
  assets/horusec-messages.jpg
  assets/steps-generate-repository-token/step1.png
  assets/steps-generate-repository-token/step10.png
  assets/steps-generate-repository-token/step11.png
  assets/steps-generate-repository-token/step12.png
  assets/steps-generate-repository-token/step13.png
  assets/steps-generate-repository-token/step14.png
  assets/steps-generate-repository-token/step2.png
  assets/steps-generate-repository-token/step3.png
  assets/steps-generate-repository-token/step4.png
  assets/steps-generate-repository-token/step5.png
  assets/steps-generate-repository-token/step6.png
  assets/steps-generate-repository-token/step7.png
  assets/steps-generate-repository-token/step8.png
  assets/steps-generate-repository-token/step9.png
  development-kit/pkg/enums/queues/queues.go
  development-kit/pkg/enums/queues/queues_test.go
  horusec-account/README.md
  horusec-analytic/README.md
  horusec-api/README.md
  horusec-auth/README.md
  horusec-cli/README.md
  horusec-cli/cmd/horusec/start/start.go
  horusec-manager/README.md
  horusec-messages/README.md
  horusec-migration/README.md
  horusec-webhook/README.md
Labels: documentation
