Repository ZupIT/horusec, pull requests merged in 2022-02, with the labels that each got.

#946 SARIF Output Support
  cmd/app/start/start.go
  internal/controllers/printresults/print_results.go
  internal/enums/outputtype/output_type.go
  internal/helpers/messages/info.go
  internal/services/sarif/sarif.go
  internal/services/sarif/sarif_test.go
  internal/services/sarif/schema.go
  internal/usecases/cli/cli.go
Labels: enhancement

#978 commitAuthors:bugfix - fix when pass invalid line to SetCommitAuthors
  internal/helpers/messages/error.go
  internal/services/formatters/csharp/dotnet_cli/formatter.go
  internal/services/formatters/csharp/scs/formatter.go
  internal/services/formatters/elixir/sobelow/formatter.go
  internal/services/formatters/generic/trivy/formatter.go
  internal/services/formatters/generic/trivy/formatter_test.go
  internal/services/formatters/go/nancy/formatter.go
  internal/services/formatters/interface.go
  internal/services/formatters/javascript/npmaudit/formatter.go
  internal/services/formatters/javascript/yarnaudit/formatter.go
  internal/services/formatters/php/phpcs/formatter.go
  internal/services/formatters/php/phpcs/formatter_test.go
  internal/services/formatters/python/safety/formatter.go
  internal/services/formatters/ruby/brakeman/formatter.go
  internal/services/formatters/ruby/bundler/formatter.go
  internal/services/formatters/ruby/bundler/formatter_test.go
  internal/services/formatters/service.go
  internal/services/formatters/service_test.go
  internal/utils/file/file.go
  internal/utils/file/file_test.go
  internal/utils/testutil/formatter_mock.go
Labels: kind/bug, kind/improvement

#967 Add missing RuleIDs
  internal/controllers/printresults/print_results.go
  internal/services/formatters/c/flawfinder/formatter.go
  internal/services/formatters/csharp/dotnet_cli/formatter.go
  internal/services/formatters/csharp/scs/formatter.go
  internal/services/formatters/elixir/mixaudit/formatter.go
  internal/services/formatters/elixir/mixaudit/mix_audit.go
  internal/services/formatters/elixir/sobelow/formatter.go
  internal/services/formatters/generic/dependency_check/formatter.go
  internal/services/formatters/generic/semgrep/formatter.go
  internal/services/formatters/generic/trivy/formatter.go
  internal/services/formatters/go/gosec/entity.go
  internal/services/formatters/go/gosec/formatter.go
  internal/services/formatters/go/nancy/formatter.go
  internal/services/formatters/go/nancy/vulnerability.go
  internal/services/formatters/hcl/checkov/formatter.go
  internal/services/formatters/hcl/tfsec/formatter.go
  internal/services/formatters/javascript/npmaudit/formatter.go
  internal/services/formatters/javascript/yarnaudit/formatter.go
  internal/services/formatters/leaks/gitleaks/formatter.go
  internal/services/formatters/php/phpcs/formatter.go
  internal/services/formatters/python/bandit/formatter.go
  internal/services/formatters/python/safety/formatter.go
  internal/services/formatters/ruby/brakeman/formatter.go
  internal/services/formatters/ruby/brakeman/output.go
  internal/services/formatters/ruby/bundler/formatter.go
  internal/services/formatters/shell/shellcheck/formatter.go
  internal/utils/vuln_hash/vuln_hash.go
Labels: kind/improvement, project/horusec-cli

#988 chore:workflow - Added new workflow to validate release workflows
  .github/workflows/build.yaml
Labels: kind/improvement, project/horusec-cli

#996 hash:feature - new hash format and handle the future depreciations
  go.mod
  go.sum
  internal/controllers/analyzer/analyzer.go
  internal/controllers/analyzer/analyzer_test.go
  internal/controllers/printresults/print_results.go
  internal/controllers/printresults/print_results_test.go
  internal/helpers/messages/warn.go
  internal/services/formatters/csharp/dotnet_cli/formatter.go
  internal/services/formatters/csharp/dotnet_cli/formatter_test.go
  internal/services/formatters/generic/trivy/formatter.go
  internal/services/formatters/service_test.go
  internal/utils/vuln_hash/vuln_hash.go
  internal/utils/vuln_hash/vuln_hash_test.go
Labels: kind/enhancement
